Repository constellation-app/constellation, pull requests merged in 2020-05, with the labels that each got.

#496 Fixed a bug preventing v1 graphs from being open.
  CHANGELOG.md
  CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/framework/GraphVisualAccess.java
Labels: v2.0.0-beta

#547 Fix to SelectableLabel
  CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/SelectableLabel.java
Labels: bug

#549 Convert Attribute editor to JavaFx pane and use TopComponent framework
  CoreAttributeEditorView/nbproject/project.xml
  CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/AttributeEditorPanel.form
  CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/AttributeEditorPanel.java
  CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/AttributeEditorTopComponent.java
Labels: enhancement

#551 Conversation view convert to TopComponent framework
  CoreConversationView/nbproject/project.xml
  CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/ConversationViewTopComponent.java
  CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/resources/conversation.css
Labels: enhancement

#552 Convert NamedSelection to TopComponent framework
  CoreNamedSelectionView/nbproject/project.xml
  CoreNamedSelectionView/src/au/gov/asd/tac/constellation/views/namedselection/NamedSelectionTopComponent.java
Labels: enhancement

#535 Added the new arrange icons
  CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/circle/ArrangeInCircleAction.java
  CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/circle/ArrangeInSphereAction.java
  CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/circle/resources/arrangeInCircle.png
  CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/circle/resources/circle3D.png
  CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/circle/resources/sphere.png
  CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/grid/ArrangeInGridAction.java
  CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/grid/resources/arrangeInGrid.png
  CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/group/ArrangeByGroupAction.java
  CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/group/ArrangeByNodeAttributeAction.java
  CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/group/resources/arrangeByNode.png
  CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/hde/HDE3DBrocolliAction.java
  CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/hde/resources/HDE.png
  CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/hierarchical/ArrangeInHierarchyAction.java
  CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/hierarchical/resources/arrangeInHierarchy.png
  CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/proximity/ArrangeByProximity2DAction.java
  CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/proximity/ArrangeByProximity3DAction.java
  CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/proximity/resources/arrangeByProximity.png
  CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/proximity/resources/arrangeByProximity3D.png
  CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/resize/ContractGraphAction.java
  CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/resize/ExpandGraphAction.java
  CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/resize/resources/contractGraph.png
  CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/resize/resources/expandGraph.png
  CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/scatter/ArrangeInScatter3dAction.java
  CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/scatter/resources/ScatterPlot3D.png
  CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/spectral/SpectralArrangementAction.java
  CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/spectral/resources/Spectral3D.png
  CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/time/LayerByTimeAction.java
  CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/time/resources/layerByTime.png
  CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/tree/ArrangeInBubbleTreeAction.java
  CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/tree/ArrangeInTreesAction.java
  CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/tree/resources/arrangeInTree.png
  CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/tree/resources/arrangeInTree3D.png
  CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/uncollide/Uncollide2DAction.java
  CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/uncollide/Uncollide3DAction.java
  CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/uncollide/resources/uncollide.png
  CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/uncollide/resources/uncollide3D.png
  CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/utilities/FlattenZFieldAction.java
  CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/utilities/resources/zflat.png
Labels: enhancement

#554 Convert Tutorial View to Top Component framework
  CoreFunctionality/nbproject/project.xml
  CoreFunctionality/src/au/gov/asd/tac/constellation/functionality/tutorial/TutorialTopComponent.java
  CoreFunctionality/src/au/gov/asd/tac/constellation/functionality/tutorial/TutorialViewPane.java
Labels: enhancement
