Repository constellation-app/constellation, pull requests merged in 2020-07, with the labels that each got.

#616 Null check and logging for plugin execution
  CoreGraphNode/src/au/gov/asd/tac/constellation/graph/node/plugins/DefaultPluginEnvironment.java
Labels: enhancement

#619 QCV and DAV null pointer
  CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/daemon/QualityControlAutoVetter.java
Labels: bug

#624 #588 infomap run on empty graph
  CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/clustering/infomap/InfoMapPlugin.java
Labels: bug

#582 Avoid view updates when hidden
  CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/AnalyticViewTopComponent.java
  CoreAttributeCalculatorView/src/au/gov/asd/tac/constellation/views/attributecalculator/AttributeCalculatorTopComponent.java
  CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/AttributeEditorTopComponent.java
  CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/ConversationViewTopComponent.java
  CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/panes/DataAccessViewTopComponent.java
  CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/LayersViewTopComponent.java
  CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/MapViewTileRenderer.java
  CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/MapViewTopComponent.java
  CorePluginReporterView/src/au/gov/asd/tac/constellation/views/pluginreporter/PluginReporterTopComponent.java
  CorePluginReporterView/src/au/gov/asd/tac/constellation/views/pluginreporter/panes/PluginReporterPane.java
  CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/QualityControlViewTopComponent.java
  CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/daemon/QualityControlAutoVetter.java
  CoreScatterPlotView/src/au/gov/asd/tac/constellation/views/scatterplot/ScatterPlotTopComponent.java
  CoreSchemaView/src/au/gov/asd/tac/constellation/views/schemaview/SchemaViewTopComponent.java
  CoreScriptingView/src/au/gov/asd/tac/constellation/views/scripting/ScriptingViewTopComponent.java
  CoreTableView/src/au/gov/asd/tac/constellation/views/tableview2/TableViewTopComponent.java
  CoreViewFramework/src/au/gov/asd/tac/constellation/views/AbstractTopComponent.java
Labels: enhancement, performance

#660 Plugin Reporter update view check
  CorePluginReporterView/src/au/gov/asd/tac/constellation/views/pluginreporter/PluginReporterTopComponent.java
  CorePluginReporterView/src/au/gov/asd/tac/constellation/views/pluginreporter/docs/pluginreporter-idx.xml
  CorePluginReporterView/src/au/gov/asd/tac/constellation/views/pluginreporter/docs/pluginreporter-map.xml
  CorePluginReporterView/src/au/gov/asd/tac/constellation/views/pluginreporter/docs/pluginreporter-toc.xml
  CorePluginReporterView/src/au/gov/asd/tac/constellation/views/pluginreporter/panes/PluginReporterPane.java
Labels: bug

#662 fix help page links
  CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/docs/arrangements-idx.xml
  CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/docs/arrangements-map.xml
  CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/docs/arrangements-toc.xml
  CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/hierarchical/ArrangeInHierarchyAction.java
  CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/tree/ArrangeInBubbleTreeAction.java
Labels: documentation

#602 Modify storage of Layers view queries and preferences
  CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/subgraph/ComponentSubgraph.java
  CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/GraphWriteMethods.java
  CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/LayersConcept.java
  CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/StoreGraph.java
  CoreGraphFramework/test/unit/src/au/gov/asd/tac/constellation/graph/StoreGraphValidator.java
  CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/LayersViewController.java
  CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/LayersViewPane.java
  CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/utilities/UpdateGraphBitmaskPlugin.java
  CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/utilities/UpdateLayerSelectionPlugin.java
  CoreLayersView/test/unit/src/au/gov/asd/tac/constellation/views/layers/utilities/LayersDualGraphSyncNGTest.java
Labels: bug

#709 :bug: switch default value to empty string
  CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/SplitNodesPlugin.java
Labels: bug

#661 Fix the Body type parameters in the Rest API
  CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/utilities/glyphs/FontInfo.java
  CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/utilities/glyphs/GlyphsFrame.java
  CoreWebServer/src/au/gov/asd/tac/constellation/webserver/api/SwaggerServlet.java
  CoreWebServer/src/au/gov/asd/tac/constellation/webserver/restapi/RestServiceUtilities.java
Labels: bug
