Repository constellation-app/constellation, pull requests merged in 2021-09, with the labels that each got.

#1336 added tooltip to welcome view recent files
  CoreWelcomeView/src/au/gov/asd/tac/constellation/views/welcome/WelcomeViewPane.java
  CoreWelcomeView/src/au/gov/asd/tac/constellation/views/welcome/resources/welcome_theme.css
Labels: enhancement, ux

#1356 JSON IO Unit Testing
  .github/workflows/build-and-scan.yml
  CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/io/ParameterIOUtilities.java
  CoreTableView/src/au/gov/asd/tac/constellation/views/tableview2/io/TableViewPreferencesIOUtilities.java
  CoreTableView/test/unit/src/au/gov/asd/tac/constellation/views/tableview2/io/TableViewPreferencesIOUtilitiesNGTest.java
  CoreUtilities/src/au/gov/asd/tac/constellation/utilities/genericjsonio/JsonIO.java
  CoreUtilities/src/au/gov/asd/tac/constellation/utilities/genericjsonio/JsonIODialog.java
  CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/genericjsonio/JsonIODialogNGTest.java
  CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/genericjsonio/JsonIONGTest.java
  CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/genericjsonio/resources/my-preferences.json
  docker/netbeans-runner/Dockerfile
Labels: testing

#1388 Fix file name not being specified in error dialog for invalid xml and updated message box title
  CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/DelimitedSourcePane.java
Labels: bug

#1392 Data Access Pane Preferences IO Refactor
  CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/DataAccessStateIoProvider.java
  CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/api/DataAccessUserPreferences.java
  CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/io/ParameterIOUtilities.java
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/api/DataAccessUserPreferencesNGTest.java
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/io/ParameterIOUtilitiesNGTest.java
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/io/resources/preferences.json
  CoreUtilities/src/au/gov/asd/tac/constellation/utilities/genericjsonio/JsonIO.java
  CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/genericjsonio/JsonIONGTest.java
Labels: testing

#1379 Bugfix/histogram clears catergory and property selection on graph element selection change #1129
  CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/HistogramState.java
  CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/HistogramTopComponent.java
  CoreWhatsNewView/src/au/gov/asd/tac/constellation/views/whatsnew/whatsnew.txt
Labels: enhancement, ux
