Repository constellation-app/constellation, pull requests merged in 2021-08, with the labels that each got.

#1154 ✅ Test TestParametersPlugin.java
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/experimental/TestParametersPluginNGTest.java
Labels: testing

#1156 Simple test for the WorkflowQueryPlugin
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/templates/WorkflowQueryPluginNGTest.java
Labels: testing

#1159 DataAccessPluginCoreType Unit Test
  CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/DataAccessPluginCoreType.java
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/DataAccessPluginCoreTypeNGTest.java
Labels: testing

#1163 DataAccessPluginType Unit tests
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/DataAccessPluginTypeNGTest.java
Labels: testing

#1161 select all plugin unit tests
  CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/utility/SelectAllPlugin.java
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/utility/SelectAllPluginNGTest.java
Labels: testing

#1162 Unit tests for MergeNodesByLocation class
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/MergeNodesByLocationNGTest.java
Labels: testing

#1157 DraggableCell Unit Test
  CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/io/DraggableCell.java
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/io/DraggableCellNGTest.java
Labels: testing

#1181 `GlobalParametersPane` Tests
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/panes/GlobalParametersPaneNGTest.java
Labels: testing

#1179 `DataAccessPreferences` Tests
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/panes/DataAccessPreferencesNGTest.java
Labels: testing

#1177 `LeadNodeSelectionDialog` Tests
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/LeadNodeSelectionDialogNGTest.java
Labels: testing

#1175 Global Parameters Unit Tests
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/GlobalParametersNGTest.java
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/resources/globalParametersTestData
Labels: testing

#1173 Unit tests for MergeNodesByType.java
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/MergeNodesByTypeNGTest.java
Labels: testing

#1172 Data Access State Unit Tests
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/DataAccessStateIoProviderNGTest.java
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/DataAccessStateNGTest.java
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/DataAccessUtilitiesNGTest.java
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/resources/dataAccessStateRead.json
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/resources/dataAccessStateWrite.json
Labels: testing

#1171 RemoveNodes Unit Tests
  CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/RemoveNodesPlugin.java
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/RemoveNodesPluginNGTest.java
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/RemoveUnusedAttributesPluginNGTest.java
  CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/StoreGraph.java
Labels: testing

#1170 Unit Tests for ExtractTypes and ExtractWords Plugins
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/importing/ExtractTypesFromTextPluginNGTest.java
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/importing/ExtractWordsFromTextPluginNGTest.java
Labels: testing

#1167 QueryPhasePane Unit Tests
  CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/panes/QueryPhasePane.java
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/panes/QueryPhasePaneNGTest.java
Labels: testing

#1155 Add basic testing for the abstract FilterPlugin class
  CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/templates/FilterPlugin.java
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/templates/FilterPluginNGTest.java
Labels: testing

#1165 ✅ Test DataAccessSearchProvider
  CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/panes/DataAccessSearchProvider.java
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/panes/DataAccessSearchProviderNGTest.java
Labels: testing

#1188 Testing Query Name Validator
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/templates/QueryNameValidatorNGTest.java
Labels: testing

#1187 Testing TSV Dropper
  CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/templates/TSVDropper.java
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/templates/TSVDropperNGTest.java
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/templates/resources/sample.tsv
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/templates/resources/sample.tsv.gz
Labels: testing

#1193 Unit tests for CoreGlobalParameters
  CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/CoreGlobalParameters.java
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/CoreGlobalParametersNGTest.java
Labels: testing

#1192 Unit tests for MergeNodeByPrefix
  CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/MergeNodesPlugin.java
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/MergeNodesByPrefixNGTest.java
Labels: testing

#1190 `PluginFinder` Tests
  CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/panes/PluginFinder.java
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/panes/PluginFinderNGTest.java
Labels: testing

#1186 Added testing for RecordStoreDropper
  CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/templates/RecordStoreDropper.java
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/templates/RecordStoreDropperNGTest.java
Labels: testing

#1185 Added testing for RecordStoreQueryPlugin
  CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/templates/RecordStoreQueryPlugin.java
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/templates/RecordStoreQueryPluginNGTest.java
Labels: testing

#1196 ✅ Test DataAccessPreferenceKeys
  CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/state/DataAccessPreferenceKeys.java
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/state/DataAccessPreferenceKeysNGTest.java
Labels: testing

#1189 `DataSourceTitledPane` Tests
  CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/panes/DataSourceTitledPane.java
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/panes/DataSourceTitledPaneNGTest.java
Labels: testing

#1194 Updated Unit Tests for MergeTransactions
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/MergeTransactionsNGTest.java
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/MergeTransactionsPluginNGTest.java
Labels: testing

#1191 Split nodes tests
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/GlobalParametersNGTest.java
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/SplitNodesPluginNGTest.java
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/SplitNodesPluginSplitLogicNGTest.java
Labels: testing

#1201 Extra unit tests for MergeNodesByPrefix
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/MergeNodesByPrefixNGTest.java
Labels: testing

#1195 Core Util Tests
  CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/utilities/MarkerCache.java
  CoreUtilities/src/au/gov/asd/tac/constellation/utilities/csv/SmartCSVWriter.java
  CoreUtilities/src/au/gov/asd/tac/constellation/utilities/datastructure/ObjectCache.java
  CoreUtilities/src/au/gov/asd/tac/constellation/utilities/text/SeparatorConstants.java
  CoreUtilities/src/au/gov/asd/tac/constellation/utilities/text/StringUtilities.java
  CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/csv/SmartCSVWriterNGTest.java
  CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/datastructure/ObjectCacheNGTest.java
  CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/text/StringUtilitiesNGTest.java
Labels: testing

#1200 ✅ Test boolean parameter type
  CorePluginFramework/test/unit/src/au/gov/asd/tac/constellation/plugins/parameters/types/BooleanParameterTypeNGTest.java
Labels: testing

#1208 Update Tags for WelcomeView Plugins
  CoreWelcomeView/src/au/gov/asd/tac/constellation/views/welcome/plugins/AddModeWelcomePlugin.java
  CoreWelcomeView/src/au/gov/asd/tac/constellation/views/welcome/plugins/DelimitedFileWelcomePlugin.java
  CoreWelcomeView/src/au/gov/asd/tac/constellation/views/welcome/plugins/JDBCImportWelcomePlugin.java
  CoreWelcomeView/src/au/gov/asd/tac/constellation/views/welcome/plugins/SelectionModeWelcomePlugin.java
  CoreWelcomeView/src/au/gov/asd/tac/constellation/views/welcome/plugins/SphereGraphWelcomePlugin.java
Labels: documentation

#1199 Table View State Unit Tests
  CoreDependencies/nbproject/project.xml
  CoreDependencies/src/ivy.xml
  CoreTableView/src/au/gov/asd/tac/constellation/views/tableview2/state/TableViewState.java
  CoreTableView/src/au/gov/asd/tac/constellation/views/tableview2/state/TableViewStateIoProvider.java
  CoreTableView/test/unit/src/au/gov/asd/tac/constellation/views/tableview2/state/TableViewConceptNGTest.java
  CoreTableView/test/unit/src/au/gov/asd/tac/constellation/views/tableview2/state/TableViewStateAttributeDescriptionNGTest.java
  CoreTableView/test/unit/src/au/gov/asd/tac/constellation/views/tableview2/state/TableViewStateIoProviderNGTest.java
  CoreTableView/test/unit/src/au/gov/asd/tac/constellation/views/tableview2/state/TableViewStateNGTest.java
  CoreTableView/test/unit/src/au/gov/asd/tac/constellation/views/tableview2/state/resources/tableViewStateRead.json
  CoreTableView/test/unit/src/au/gov/asd/tac/constellation/views/tableview2/state/resources/tableViewStateWrite.json
Labels: testing

#1204 Update tags for NotesView plugins
  CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewController.java
Labels: documentation

#1212 Update/add tags to CoreTableView plugins
  CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/delete/DeleteSelectionPlugin.java
  CoreTableView/src/au/gov/asd/tac/constellation/views/tableview/CopyDataToClipboard.java
  CoreTableView/src/au/gov/asd/tac/constellation/views/tableview/CopyDataToExcelFile.java
  CoreTableView/src/au/gov/asd/tac/constellation/views/tableview/TableViewTopComponent.java
  CoreTableView/src/au/gov/asd/tac/constellation/views/tableview2/TableViewUtilities.java
Labels: documentation

#1207 Update tags for CoreConversationView plugins
  CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/AddContentAttributesPlugin.java
  CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/ConversationBox.java
  CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/TranslationConversationContributionProvider.java
Labels: documentation

#1209 Table View IO Tests
  CoreTableView/src/au/gov/asd/tac/constellation/views/tableview2/io/TableViewPreferencesIOUtilities.java
  CoreTableView/test/unit/src/au/gov/asd/tac/constellation/views/tableview2/io/TableViewPreferencesIOUtilitiesNGTest.java
  CoreTableView/test/unit/src/au/gov/asd/tac/constellation/views/tableview2/io/resources/transaction-preferences.json
  CoreTableView/test/unit/src/au/gov/asd/tac/constellation/views/tableview2/io/resources/vertex-preferences.json
Labels: testing

#1230 `TableViewUtilities` Unit Tests
  CoreTableView/src/au/gov/asd/tac/constellation/views/tableview2/TableViewUtilities.java
  CoreTableView/test/unit/src/au/gov/asd/tac/constellation/views/tableview2/ShowInTableViewContextMenuProviderNGTest.java
  CoreTableView/test/unit/src/au/gov/asd/tac/constellation/views/tableview2/TableViewUtilitiesNGTest.java
  CoreTableView/test/unit/src/au/gov/asd/tac/constellation/views/tableview2/state/TableViewStateIoProviderNGTest.java
Labels: testing

#1245 BugFix For Failing Test
  CoreTableView/src/au/gov/asd/tac/constellation/views/tableview2/TableViewUtilities.java
Labels: bug

#1183 `MergeNodesPlugin` Unit Tests
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/MergeNodesPluginNGTest.java
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/TestMergeType.java
Labels: testing

#1234 Add test listener to test triggering of listeners
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/panes/HeadingPaneNGTest.java
Labels: testing

#1205 Update tags for CoreHistogramView plugins
  CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/HistogramClearFilterPlugin.java
  CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/HistogramFilterOnSelectionPlugin.java
  CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/HistogramTopComponent.java
Labels: documentation

#1257 Update tags for CoreInteractiveGraph plugins
  CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/gui/VisualGraphOpener.java
  CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/gui/VisualGraphTopComponent.java
  CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/clipboard/ClipboardUtilities.java
  CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/clipboard/CopyToClipboardAction.java
  CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/clipboard/CopyToClipboardPlugin.java
  CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/clipboard/CopyToNewGraphPlugin.java
  CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/clipboard/CutToClipboardAction.java
  CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/clipboard/CutToClipboardPlugin.java
  CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/clipboard/PasteFromClipboardAction.java
  CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/clipboard/PasteFromClipboardPlugin.java
  CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/clipboard/PasteGraphPlugin.java
  CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/clipboard/PasteTextPlugin.java
  CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/composite/ContractAllCompositesPlugin.java
  CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/composite/ContractCompositePlugin.java
  CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/composite/CreateCompositeFromSelectionPlugin.java
  CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/composite/CreateCompositesFromDominantNodesPlugin.java
  CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/composite/DestroyAllCompositesPlugin.java
  CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/composite/DestroyCompositePlugin.java
  CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/composite/ExpandAllCompositesPlugin.java
  CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/composite/ExpandCompositePlugin.java
  CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/display/SetConnectionModePlugin.java
  CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/display/SetDrawFlagPlugin.java
  CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/display/SetVisibleAboveThresholdPlugin.java
  CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/display/ToggleDisplayModePlugin.java
  CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/display/ToggleDrawFlagPlugin.java
  CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/draw/CreateTransactionPlugin.java
  CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/draw/CreateVertexPlugin.java
  CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/draw/ToggleDrawDirectedPlugin.java
  CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/draw/ToggleSelectionModePlugin.java
  CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/io/AutosaveGraphPlugin.java
  CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/io/CloseGraphPlugin.java
  CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/io/SaveGraphPlugin.java
  CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/select/BoxSelectionPlugin.java
  CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/zoom/PreviousViewPlugin.java
  CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/zoom/ResetViewPlugin.java
  CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/zoom/RotateCameraPlugin.java
  CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/zoom/SetCameraVisibilityRange.java
  CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/zoom/ZoomToSelectionPlugin.java
  CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/zoom/ZoomToVerticesPlugin.java
  CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/visual/DefaultInteractionEventHandler.java
  CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/plugins/CompleteSchemaPlugin.java
Labels: documentation

#1217 HeadingPane Unit Tests
  CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/panes/HeadingPane.java
  CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/panes/HeadingPaneNGTest.java
Labels: testing

#1259 Update save plugins to EXPORT
  CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/io/AutosaveGraphPlugin.java
  CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/io/SaveGraphPlugin.java
Labels: documentation

#1265 Move Notes View to Views menu
  CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewTopComponent.java
  CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/docs/notes-view.html
  CorePluginReporterView/src/au/gov/asd/tac/constellation/views/pluginreporter/PluginReporterTopComponent.java
  CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/QualityControlViewTopComponent.java
  CoreScatterPlotView/src/au/gov/asd/tac/constellation/views/scatterplot/ScatterPlotTopComponent.java
  CoreSchemaView/src/au/gov/asd/tac/constellation/views/schemaview/SchemaViewTopComponent.java
  CoreScriptingView/src/au/gov/asd/tac/constellation/views/scripting/ScriptingViewTopComponent.java
  CoreTableView/src/au/gov/asd/tac/constellation/views/tableview2/TableViewTopComponent.java
  CoreTimelineView/src/au/gov/asd/tac/constellation/views/timeline/TimelineTopComponent.java
  CoreWhatsNewView/src/au/gov/asd/tac/constellation/views/whatsnew/whatsnew.txt
Labels: enhancement, ux

#1316 Fix unintended user note deletion bug
  CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewPane.java
  CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewTopComponent.java
Labels: bug, v2.4.0-rc
